version: 2
updates:
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Monitor Docker images
  - package-ecosystem: "docker"
    directory: "/infra/templates/ubuntu-devcontainer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
