# Starship configuration file
# See https://starship.rs/config/ for more options

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[➜](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = ' '
truncation_length = 20
truncation_symbol = '…'

[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '

[directory]
truncation_length = 3
truncate_to_repo = false
read_only = ' 󰌾'

[cmd_duration]
min_time = 500
format = ' [$duration](bold yellow)'

[time]
disabled = false
format = ' [$time]($style) '
time_format = '%T'

[python]
symbol = ' '

[nodejs]
symbol = ' '

[rust]
symbol = ' '

[docker_context]
symbol = ' '