[general]
import = ["themes/solarized_dark.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 1.0
decorations = "full"
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 12
y = 6

[scrolling]
history = 10000

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]
draw_bold_text_with_bright_colors = true