[general]
import = ["~/.config/alacritty/themes/solarized_dark.toml"]

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 1.0
decorations = "none"
dynamic_title = true

[window.padding]
x = 12
y = 6

[scrolling]
history = 10000

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]
draw_bold_text_with_bright_colors = true