# Multi-line prompt format
format = """
($status$cmd_duration â˜ï¸  $gcloud$aws $line_break)\
$username@$hostname $shell ğŸ“‚ $directory$git_branch$git_status\
$line_break\
$character"""

[kubernetes]
disabled = true

[aws]
format = ' | [$profile]($style)'
style = 'bold blue'

[gcloud]
format = '[$account(@$domain)]($style)'
style = 'bold yellow'

[time]
disabled = true

[status]
disabled = false
format = "âŒ [$status]($style) "
style = "red"

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
format = "â±ï¸  [$duration]($style)"
style = "yellow"

[directory]
truncation_length = 0
fish_style_pwd_dir_length = 1
truncate_to_repo = false


[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold green"
format = "[$hostname](bold green)"

[shell]
disabled = false
format = "[$indicator]($style) "
bash_indicator = "î¯‡"
powershell_indicator = "ó°¨Š"
fish_indicator = "ğŸŸ"
zsh_indicator = "âš¡"
cmd_indicator = "ğŸ’»"
style = "cyan bold"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
