# Multi-line prompt format
format = """
($status$cmd_duration â˜ï¸  $gcloud$aws $line_break)\
ğŸ“‚ $directory$git_branch$git_status\
$line_break\
$character"""

[kubernetes]
disabled = true

[aws]
format = ' | [$profile]($style)'
style = 'bold blue'

[gcloud]
format = '[$account(@$domain)]($style)'
style = 'bold yellow'

[time]
disabled = true

[status]
disabled = false
format = "âŒ [$status]($style) "
style = "red"

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
format = "â±ï¸  [$duration]($style)"
style = "yellow"

[directory]
truncation_length = 0
fish_style_pwd_dir_length = 1
truncate_to_repo = false


[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
